import type { CommodityDef, CommodityId } from "../types";

export const COMMODITIES: Record<CommodityId, CommodityDef> = {
  rice: {
    id: "rice",
    name: "Rice",
    emoji: "🌾",
    unit: "sack",
    basePrice: 12_000,
    perishable: true,
    spoilRate: 0.03,
    category: "food",
    availableEverywhere: true,
  },
  coffee: {
    id: "coffee",
    name: "Coffee",
    emoji: "☕",
    unit: "kg",
    basePrice: 42_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
    availableEverywhere: true,
  },
  sugar: {
    id: "sugar",
    name: "Sugar",
    emoji: "🍬",
    unit: "kg",
    basePrice: 15_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
    availableEverywhere: true,
  },
  fish: {
    id: "fish",
    name: "Fish",
    emoji: "🐟",
    unit: "kg",
    basePrice: 35_000,
    perishable: true,
    spoilRate: 0.08,
    category: "food",
    availableEverywhere: true,
  },
  rubber: {
    id: "rubber",
    name: "Rubber",
    emoji: "🛞",
    unit: "kg",
    basePrice: 22_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  steel: {
    id: "steel",
    name: "Steel",
    emoji: "🔩",
    unit: "ton",
    basePrice: 180_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  electronics: {
    id: "electronics",
    name: "Electronics",
    emoji: "💻",
    unit: "unit",
    basePrice: 250_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  fuel: {
    id: "fuel",
    name: "Fuel",
    emoji: "⛽",
    unit: "liter",
    basePrice: 8_500,
    perishable: false,
    spoilRate: 0,
    category: "fuel",
    availableEverywhere: true,
  },
  medicine: {
    id: "medicine",
    name: "Medicine",
    emoji: "💊",
    unit: "box",
    basePrice: 85_000,
    perishable: true,
    spoilRate: 0.02,
    category: "medical",
    availableEverywhere: true,
  },
  clothing: {
    id: "clothing",
    name: "Clothing",
    emoji: "👕",
    unit: "bale",
    basePrice: 65_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: true,
  },
  construction: {
    id: "construction",
    name: "Construction Materials",
    emoji: "🧱",
    unit: "unit",
    basePrice: 55_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  rendang: {
    id: "rendang",
    name: "Rendang",
    emoji: "🥘",
    unit: "jar",
    basePrice: 95_000,
    perishable: true,
    spoilRate: 0.04,
    category: "food",
    availableEverywhere: false,
  },
  pempek: {
    id: "pempek",
    name: "Pempek",
    emoji: "🍥",
    unit: "box",
    basePrice: 70_000,
    perishable: true,
    spoilRate: 0.06,
    category: "food",
    availableEverywhere: false,
  },
  batik: {
    id: "batik",
    name: "Batik",
    emoji: "🎨",
    unit: "piece",
    basePrice: 150_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: false,
  },
  sasirangan: {
    id: "sasirangan",
    name: "Sasirangan",
    emoji: "🧵",
    unit: "piece",
    basePrice: 135_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: false,
  },
  jewelry: {
    id: "jewelry",
    name: "Gold Jewelry",
    emoji: "💍",
    unit: "piece",
    basePrice: 280_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: false,
  },
  silk: {
    id: "silk",
    name: "Silk Sarong",
    emoji: "🧣",
    unit: "piece",
    basePrice: 160_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: false,
  },
  nutmeg: {
    id: "nutmeg",
    name: "Nutmeg",
    emoji: "🌰",
    unit: "sack",
    basePrice: 85_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
    availableEverywhere: false,
  },
  noken: {
    id: "noken",
    name: "Noken Bag",
    emoji: "👜",
    unit: "piece",
    basePrice: 150_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: false,
  },
  palm_oil: {
    id: "palm_oil",
    name: "Palm Oil",
    emoji: "🫙",
    unit: "liter",
    basePrice: 15_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  tea: {
    id: "tea",
    name: "Tea",
    emoji: "🍵",
    unit: "kg",
    basePrice: 30_000,
    perishable: true,
    spoilRate: 0.02,
    category: "food",
    availableEverywhere: true,
  },
  cocoa: {
    id: "cocoa",
    name: "Cocoa",
    emoji: "🍫",
    unit: "kg",
    basePrice: 52_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
    availableEverywhere: true,
  },
  banana: {
    id: "banana",
    name: "Banana",
    emoji: "🍌",
    unit: "kg",
    basePrice: 8_000,
    perishable: true,
    spoilRate: 0.04,
    category: "food",
    availableEverywhere: true,
  },
  mango: {
    id: "mango",
    name: "Mango",
    emoji: "🥭",
    unit: "kg",
    basePrice: 22_000,
    perishable: true,
    spoilRate: 0.04,
    category: "food",
    availableEverywhere: true,
  },
  chili: {
    id: "chili",
    name: "Chili",
    emoji: "🌶️",
    unit: "kg",
    basePrice: 28_000,
    perishable: true,
    spoilRate: 0.06,
    category: "food",
    availableEverywhere: true,
  },
  soybeans: {
    id: "soybeans",
    name: "Soybeans",
    emoji: "🫘",
    unit: "sack",
    basePrice: 16_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
    availableEverywhere: true,
  },
  tempeh: {
    id: "tempeh",
    name: "Tempeh",
    emoji: "🧆",
    unit: "box",
    basePrice: 12_000,
    perishable: true,
    spoilRate: 0.05,
    category: "food",
    availableEverywhere: true,
  },
  tofu: {
    id: "tofu",
    name: "Tofu",
    emoji: "🧊",
    unit: "block",
    basePrice: 9_000,
    perishable: true,
    spoilRate: 0.05,
    category: "food",
    availableEverywhere: true,
  },
  chicken: {
    id: "chicken",
    name: "Chicken",
    emoji: "🍗",
    unit: "kg",
    basePrice: 38_000,
    perishable: true,
    spoilRate: 0.06,
    category: "food",
    availableEverywhere: true,
  },
  beef: {
    id: "beef",
    name: "Beef",
    emoji: "🥩",
    unit: "kg",
    basePrice: 85_000,
    perishable: true,
    spoilRate: 0.06,
    category: "food",
    availableEverywhere: true,
  },
  eggs: {
    id: "eggs",
    name: "Eggs",
    emoji: "🥚",
    unit: "crate",
    basePrice: 25_000,
    perishable: true,
    spoilRate: 0.05,
    category: "food",
    availableEverywhere: true,
  },
  milk: {
    id: "milk",
    name: "Milk",
    emoji: "🥛",
    unit: "liter",
    basePrice: 14_000,
    perishable: true,
    spoilRate: 0.08,
    category: "food",
    availableEverywhere: true,
  },
  salt: {
    id: "salt",
    name: "Salt",
    emoji: "🧂",
    unit: "sack",
    basePrice: 5_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
    availableEverywhere: true,
  },
  cement: {
    id: "cement",
    name: "Cement",
    emoji: "🏗️",
    unit: "sack",
    basePrice: 45_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  timber: {
    id: "timber",
    name: "Timber",
    emoji: "🪵",
    unit: "ton",
    basePrice: 95_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  glass: {
    id: "glass",
    name: "Glass",
    emoji: "🪟",
    unit: "crate",
    basePrice: 60_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  ceramics: {
    id: "ceramics",
    name: "Ceramics",
    emoji: "🏺",
    unit: "crate",
    basePrice: 48_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  paint: {
    id: "paint",
    name: "Paint",
    emoji: "🖌️",
    unit: "can",
    basePrice: 34_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  rope: {
    id: "rope",
    name: "Rope",
    emoji: "🪢",
    unit: "coil",
    basePrice: 18_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  nails: {
    id: "nails",
    name: "Nails",
    emoji: "📌",
    unit: "box",
    basePrice: 12_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  paper: {
    id: "paper",
    name: "Paper",
    emoji: "📄",
    unit: "ream",
    basePrice: 20_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  batteries: {
    id: "batteries",
    name: "Batteries",
    emoji: "🔋",
    unit: "pack",
    basePrice: 40_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  carparts: {
    id: "carparts",
    name: "Car Parts",
    emoji: "🔧",
    unit: "crate",
    basePrice: 95_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  fertilizer: {
    id: "fertilizer",
    name: "Fertilizer",
    emoji: "🌱",
    unit: "sack",
    basePrice: 30_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
    availableEverywhere: true,
  },
  orchid: {
    id: "orchid",
    name: "Orchid",
    emoji: "🌺",
    unit: "plant",
    basePrice: 45_000,
    perishable: true,
    spoilRate: 0.02,
    category: "luxury",
    availableEverywhere: false,
  },
  lumpia: {
    id: "lumpia",
    name: "Lumpia",
    emoji: "🌯",
    unit: "dozen",
    basePrice: 18_000,
    perishable: true,
    spoilRate: 0.04,
    category: "food",
    availableEverywhere: false,
  },
  apples: {
    id: "apples",
    name: "Apples",
    emoji: "🍎",
    unit: "kg",
    basePrice: 25_000,
    perishable: true,
    spoilRate: 0.04,
    category: "food",
    availableEverywhere: false,
  },
  durian: {
    id: "durian",
    name: "Durian",
    emoji: "🍈",
    unit: "fruit",
    basePrice: 40_000,
    perishable: true,
    spoilRate: 0.05,
    category: "food",
    availableEverywhere: false,
  },
  pearls: {
    id: "pearls",
    name: "Lombok Pearls",
    emoji: "🦪",
    unit: "string",
    basePrice: 350_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: false,
  },
  ulos: {
    id: "ulos",
    name: "Ulos Weave",
    emoji: "🧶",
    unit: "piece",
    basePrice: 120_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
    availableEverywhere: false,
  },
};

export const ALL_COMMODITY_IDS = Object.keys(COMMODITIES) as CommodityId[];