import type { CommodityDef, CommodityId } from "../types";

export const COMMODITIES: Record<CommodityId, CommodityDef> = {
  rice: {
    id: "rice",
    name: "Rice",
    emoji: "🌾",
    unit: "sack",
    basePrice: 12_000,
    perishable: true,
    spoilRate: 0.03,
    category: "food",
  },
  coffee: {
    id: "coffee",
    name: "Coffee",
    emoji: "☕",
    unit: "kg",
    basePrice: 42_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
  },
  sugar: {
    id: "sugar",
    name: "Sugar",
    emoji: "🍬",
    unit: "kg",
    basePrice: 15_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
  },
  fish: {
    id: "fish",
    name: "Fish",
    emoji: "🐟",
    unit: "kg",
    basePrice: 35_000,
    perishable: true,
    spoilRate: 0.08,
    category: "food",
  },
  rubber: {
    id: "rubber",
    name: "Rubber",
    emoji: "🛞",
    unit: "kg",
    basePrice: 22_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
  },
  steel: {
    id: "steel",
    name: "Steel",
    emoji: "🔩",
    unit: "ton",
    basePrice: 180_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
  },
  electronics: {
    id: "electronics",
    name: "Electronics",
    emoji: "💻",
    unit: "unit",
    basePrice: 250_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
  },
  fuel: {
    id: "fuel",
    name: "Fuel",
    emoji: "⛽",
    unit: "liter",
    basePrice: 8_500,
    perishable: false,
    spoilRate: 0,
    category: "fuel",
  },
  medicine: {
    id: "medicine",
    name: "Medicine",
    emoji: "💊",
    unit: "box",
    basePrice: 85_000,
    perishable: true,
    spoilRate: 0.02,
    category: "medical",
  },
  clothing: {
    id: "clothing",
    name: "Clothing",
    emoji: "👕",
    unit: "bale",
    basePrice: 65_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
  },
  construction: {
    id: "construction",
    name: "Construction Materials",
    emoji: "🧱",
    unit: "unit",
    basePrice: 55_000,
    perishable: false,
    spoilRate: 0,
    category: "industrial",
  },
  rendang: {
    id: "rendang",
    name: "Rendang",
    emoji: "🥘",
    unit: "jar",
    basePrice: 95_000,
    perishable: true,
    spoilRate: 0.04,
    category: "food",
  },
  pempek: {
    id: "pempek",
    name: "Pempek",
    emoji: "🍥",
    unit: "box",
    basePrice: 70_000,
    perishable: true,
    spoilRate: 0.06,
    category: "food",
  },
  batik: {
    id: "batik",
    name: "Batik",
    emoji: "🎨",
    unit: "piece",
    basePrice: 150_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
  },
  sasirangan: {
    id: "sasirangan",
    name: "Sasirangan",
    emoji: "🧵",
    unit: "piece",
    basePrice: 135_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
  },
  jewelry: {
    id: "jewelry",
    name: "Gold Jewelry",
    emoji: "💍",
    unit: "piece",
    basePrice: 280_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
  },
  silk: {
    id: "silk",
    name: "Silk Sarong",
    emoji: "🧣",
    unit: "piece",
    basePrice: 160_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
  },
  nutmeg: {
    id: "nutmeg",
    name: "Nutmeg",
    emoji: "🌰",
    unit: "sack",
    basePrice: 85_000,
    perishable: false,
    spoilRate: 0,
    category: "food",
  },
  noken: {
    id: "noken",
    name: "Noken Bag",
    emoji: "👜",
    unit: "piece",
    basePrice: 150_000,
    perishable: false,
    spoilRate: 0,
    category: "luxury",
  },
};

export const ALL_COMMODITY_IDS = Object.keys(COMMODITIES) as CommodityId[];
